spring.application.name=helloworld
# The default local address where the Ollama engine runs
spring.ai.ollama.base-url=http://localhost:11434

# Instruct Spring AI to explicitly target your local Llama 3 model
spring.ai.ollama.chat.options.model=llama3

# Optional: Auto-download the model at startup if it's missing from your system
spring.ai.ollama.init.pull-model=when-missing

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
server.port=9999