spring.application.name=helloworld
# The default local address where the Ollama engine runs
spring.ai.ollama.base-url=http://localhost:11434

# Instruct Spring AI to explicitly target your local Llama 3 model
spring.ai.ollama.chat.options.model=llama3

# Optional: Auto-download the model at startup if it's missing from your system
spring.ai.ollama.init.pull-model=when-missing

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
server.port=9999

# Change the default Swagger UI path
#springdoc.swagger-ui.path=/api-docs.html

# Disable Swagger UI entirely for production profiles
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


#spring.ai.ollama.embedding.options.model=llama3
#spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text

ai.vectorstore.pgvector.initialize-schemae=true
ai.vectorstore.pgvector.table-name=public.vector_store
ai.vectorstore.pgvector.index-type=HNSW
ai.vectorstore.pgvector.dimensions=1536
ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
ai.vectorstore.pgvector.max-document-batch-size=10000 # Optional: Maximum number of documents per batch

